apiVersion: v1
kind: Service
metadata:
  labels:
    app: tracking
  name: tracking
  namespace: fraudwall
spec:
  ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: tracking
  type: ClusterIP